query Blog($slug: String!) {
  BlogPost(
    postSlug: $slug
  ) {
    postTags
    postImage {
      url
    }
    postTitle
    postContent
    postDateAndTime
    authors {
      authorName
      authorImage {
        url
      }
      authorBibliography
    }
  }
}
